import { onMessagePublished } from 'firebase-functions/v2/pubsub';
import { GeminiService } from '../../services/gemini.service';
import { OpenAIService } from '../../services/openai.service';
import { WordPressService } from '../../services/wordpress.service';
import { App } from '@slack/bolt';
import { config } from '../../config';

let geminiService: GeminiService;
let openaiService: OpenAIService;
let wpService: WordPressService;

import {
    SLACK_BOT_TOKEN,
    SLACK_SIGNING_SECRET,
    GEMINI_API_KEY,
    OPENAI_API_KEY,
    WP_BASE_URL,
    WP_API_USER,
    WP_API_APP_PASSWORD,
    GOOGLE_SHEETS_CREDENTIALS,
    SPREADSHEET_ID,
    SLACK_CHANNEL_ID
} from '../../config';

const secretsArray = [
    SLACK_BOT_TOKEN,
    SLACK_SIGNING_SECRET,
    GEMINI_API_KEY,
    OPENAI_API_KEY,
    WP_BASE_URL,
    WP_API_USER,
    WP_API_APP_PASSWORD,
    GOOGLE_SHEETS_CREDENTIALS,
    SPREADSHEET_ID,
    SLACK_CHANNEL_ID
];

export const generateBlogDraftPubSub = (getSlackApp: () => App) => {
    return onMessagePublished({ topic: 'generate-blog-draft', secrets: secretsArray }, async (event) => {
        try {
            geminiService = geminiService || new GeminiService();
            openaiService = openaiService || new OpenAIService();
            wpService = wpService || new WordPressService();

            const slackApp = getSlackApp();
            const payload = event.data.message.json;
            const { title, content, generateImage } = payload;

            console.log(`Processing draft for: ${title}`);

            // 1. Generate Korean Draft
            const draftResult = await geminiService.generateKoreanDraft(title, content);
            let htmlContent = draftResult.content;

            // 2. Generate and Upload Image if requested
            let mediaId: number | undefined;
            if (generateImage) {
                console.log('Generating image with DALL-E 3...');
                const imageBuffer = await openaiService.generateImage(draftResult.title);
                console.log('Uploading image to WordPress...');
                mediaId = await wpService.uploadMedia(imageBuffer, `blog-image-${Date.now()}.png`);
                const mediaUrl = await wpService.getMediaUrl(mediaId);

                // Replace [[IMAGE]] placeholder in content
                const imgTag = `<figure class="wp-block-image size-large"><img src="${mediaUrl}" alt="blog image" style="width:100%; height:auto;" /><figcaption class="wp-element-caption">This is an image generated by AI</figcaption></figure>`;
                htmlContent = htmlContent.replace('[[IMAGE]]', imgTag);
            } else {
                htmlContent = htmlContent.replace('[[IMAGE]]', '');
            }

            // 3. Create Draft Post in WordPress
            console.log('Creating draft post in WordPress...');
            const post = await wpService.createDraftPost({
                title: draftResult.title,
                content: htmlContent,
                featuredMediaId: mediaId
            });

            // 4. Send Slack Message with "Approve" button
            console.log('Sending Slack message...');
            await slackApp.client.chat.postMessage({
                token: config.slack.botToken as string,
                channel: config.slack.channelId as string, // Unified channel instead of userId DM
                text: '대표님, 블로그 초안 생성이 완료되었습니다.',
                blocks: [
                    {
                        type: "header",
                        text: {
                            type: "plain_text",
                            text: "📝 블로그 초안",
                            emoji: true
                        }
                    },
                    {
                        type: "section",
                        text: {
                            type: "plain_text",
                            text: `- ${draftResult.title}`,
                            emoji: true
                        }
                    },
                    {
                        type: "section",
                        text: {
                            type: "plain_text",
                            text: "대표님, 블로그 초안 생성이 완료되었습니다."
                        }
                    },
                    {
                        type: "actions",
                        elements: [
                            {
                                type: "button",
                                text: {
                                    type: "plain_text",
                                    text: "✏️ 워드프레스에서 확인하기",
                                    emoji: true
                                },
                                url: `${config.wordpress.baseUrl}/wp-admin/post.php?post=${post.id}&action=edit`
                            },
                            {
                                type: "button",
                                text: {
                                    type: "plain_text",
                                    text: "🚀 확정 및 변환 시작",
                                    emoji: true
                                },
                                style: "primary",
                                value: post.id.toString(),
                                action_id: "start_final_step"
                            }
                        ]
                    }
                ]
            });
            console.log('Draft generation process completed.');
        } catch (error) {
            console.error('Error processing draft:', error);
        }
    });
};
