"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateBlogDraftPubSub = void 0;
const pubsub_1 = require("firebase-functions/v2/pubsub");
const gemini_service_1 = require("../../services/gemini.service");
const openai_service_1 = require("../../services/openai.service");
const wordpress_service_1 = require("../../services/wordpress.service");
const config_1 = require("../../config");
let geminiService;
let openaiService;
let wpService;
const config_2 = require("../../config");
const secretsArray = [
    config_2.SLACK_BOT_TOKEN,
    config_2.SLACK_SIGNING_SECRET,
    config_2.GEMINI_API_KEY,
    config_2.OPENAI_API_KEY,
    config_2.WP_BASE_URL,
    config_2.WP_API_USER,
    config_2.WP_API_APP_PASSWORD,
    config_2.GOOGLE_SHEETS_CREDENTIALS,
    config_2.SPREADSHEET_ID,
    config_2.SLACK_CHANNEL_ID
];
const generateBlogDraftPubSub = (getSlackApp) => {
    return (0, pubsub_1.onMessagePublished)({ topic: 'generate-blog-draft', secrets: secretsArray }, async (event) => {
        try {
            geminiService = geminiService || new gemini_service_1.GeminiService();
            openaiService = openaiService || new openai_service_1.OpenAIService();
            wpService = wpService || new wordpress_service_1.WordPressService();
            const slackApp = getSlackApp();
            const payload = event.data.message.json;
            const { title, content, generateImage } = payload;
            console.log(`Processing draft for: ${title}`);
            // 1. Generate Korean Draft
            const draftResult = await geminiService.generateKoreanDraft(title, content);
            let htmlContent = draftResult.content;
            // 2. Generate and Upload Image if requested
            let mediaId;
            if (generateImage) {
                console.log('Generating image with DALL-E 3...');
                const imageBuffer = await openaiService.generateImage(draftResult.title);
                console.log('Uploading image to WordPress...');
                mediaId = await wpService.uploadMedia(imageBuffer, `blog-image-${Date.now()}.png`);
                const mediaUrl = await wpService.getMediaUrl(mediaId);
                // Replace [[IMAGE]] placeholder in content
                const imgTag = `<figure class="wp-block-image size-large"><img src="${mediaUrl}" alt="blog image" style="width:100%; height:auto;" /><figcaption class="wp-element-caption">This is an image generated by AI</figcaption></figure>`;
                htmlContent = htmlContent.replace('[[IMAGE]]', imgTag);
            }
            else {
                htmlContent = htmlContent.replace('[[IMAGE]]', '');
            }
            // 3. Create Draft Post in WordPress
            console.log('Creating draft post in WordPress...');
            const post = await wpService.createDraftPost({
                title: draftResult.title,
                content: htmlContent,
                featuredMediaId: mediaId
            });
            // 4. Send Slack Message with "Approve" button
            console.log('Sending Slack message...');
            await slackApp.client.chat.postMessage({
                token: config_1.config.slack.botToken,
                channel: config_1.config.slack.channelId, // Unified channel instead of userId DM
                text: '대표님, 블로그 초안 생성이 완료되었습니다.',
                blocks: [
                    {
                        type: "header",
                        text: {
                            type: "plain_text",
                            text: "📝 블로그 초안",
                            emoji: true
                        }
                    },
                    {
                        type: "section",
                        text: {
                            type: "plain_text",
                            text: `- ${draftResult.title}`,
                            emoji: true
                        }
                    },
                    {
                        type: "section",
                        text: {
                            type: "plain_text",
                            text: "대표님, 블로그 초안 생성이 완료되었습니다."
                        }
                    },
                    {
                        type: "actions",
                        elements: [
                            {
                                type: "button",
                                text: {
                                    type: "plain_text",
                                    text: "✏️ 워드프레스에서 확인하기",
                                    emoji: true
                                },
                                url: `${config_1.config.wordpress.baseUrl}/wp-admin/post.php?post=${post.id}&action=edit`
                            },
                            {
                                type: "button",
                                text: {
                                    type: "plain_text",
                                    text: "🚀 확정 및 변환 시작",
                                    emoji: true
                                },
                                style: "primary",
                                value: post.id.toString(),
                                action_id: "start_final_step"
                            }
                        ]
                    }
                ]
            });
            console.log('Draft generation process completed.');
        }
        catch (error) {
            console.error('Error processing draft:', error);
        }
    });
};
exports.generateBlogDraftPubSub = generateBlogDraftPubSub;
//# sourceMappingURL=draft.pubsub.js.map